#!/bin/bash
[% c("var/set_default_env") -%]
tar xf [% project %]-[% c("version") %].tar.gz
mv [% project %]-[% c("version") %] [% project %]
cd [% project %]
# We want to make sure we can avoid timestamps in PE headers.
patch -p1 < $rootdir/timestamp.patch
cd ..
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
